# Survey Dataset

I will analyse some data regarding the emerging technologies

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv"

In [4]:
df= pd.read_csv(dataset_url)
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

In [5]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11552 entries, 0 to 11551
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              11552 non-null  int64
 1   MainBranch              11552 non-null  object
 2   Hobbyist                11552 non-null  object
 3   OpenSourcer             11552 non-null  object
 4   OpenSource              11471 non-null  object
 5   Employment              11552 non-null  object
 6   Country                 11552 non-null  object
 7   Student                 11499 non-null  object
 8   EdLevel                 11436 non-null  object
 9   UndergradMajor          10812 non-null  object
 10  EduOther                11388 non-null  object
 11  OrgSize                 11454 non-null  object
 12  DevType                 11485 non-null  object
 13  YearsCode               11543 non-null  object
 14  Age1stCode              11539 non-null  object
 15  YearsCodePro            11536 non-null  object
 16  CareerSat               11552 non-null  object
 17  JobSat                  11551 non-null  object
 18  MgrIdiot                11054 non-null  object
 19  MgrMoney                11050 non-null  object
 20  MgrWant                 11054 non-null  object
 21  JobSeek                 11552 non-null  object
 22  LastHireDate            11552 non-null  object
 23  LastInt                 11129 non-null  object
 24  FizzBuzz                11515 non-null  object
 25  JobFactors              11549 non-null  object
 26  ResumeUpdate            11511 non-null  object
 27  CurrencySymbol          11552 non-null  object
 28  CurrencyDesc            11552 non-null  object
 29  CompTotal               10737 non-null  float64
 30  CompFreq                11346 non-null  object
 31  ConvertedComp           10730 non-null  float64
 32  WorkWeekHrs             11427 non-null  float64
 33  WorkPlan                11429 non-null  object
 34  WorkChallenge           11384 non-null  object
 35  WorkRemote              11544 non-null  object
 36  WorkLoc                 11520 non-null  object
 37  ImpSyn                  11547 non-null  object
 38  CodeRev                 11551 non-null  object
 39  CodeRevHrs              9083 non-null   float64
 40  UnitTests               11523 non-null  object
 41  PurchaseHow             11354 non-null  object
 42  PurchaseWhat            11514 non-null  object
 43  LanguageWorkedWith      11541 non-null  object
 44  LanguageDesireNextYear  11415 non-null  object
 45  DatabaseWorkedWith      11096 non-null  object
 46  DatabaseDesireNextYear  10497 non-null  object
 47  PlatformWorkedWith      11130 non-null  object
 48  PlatformDesireNextYear  10991 non-null  object
 49  WebFrameWorkedWith      10139 non-null  object
 50  WebFrameDesireNextYear  9918 non-null   object
 51  MiscTechWorkedWith      9343 non-null   object
 52  MiscTechDesireNextYear  10078 non-null  object
 53  DevEnviron              11523 non-null  object
 54  OpSys                   11518 non-null  object
 55  Containers              11470 non-null  object
 56  BlockchainOrg           9198 non-null   object
 57  BlockchainIs            8915 non-null   object
 58  BetterLife              11452 non-null  object
 59  ITperson                11517 non-null  object
 60  OffOn                   11514 non-null  object
 61  SocialMedia             11251 non-null  object
 62  Extraversion            11532 non-null  object
 63  ScreenName              11039 non-null  object
 64  SOVisit1st              11227 non-null  object
 65  SOVisitFreq             11547 non-null  object
 66  SOVisitTo               11551 non-null  object
 67  SOFindAnswer            11549 non-null  object
 68  SOTimeSaved             11501 non-null  object
 69  SOHowMuchTime           9616 non-null   object
 70  SOAccount               11551 non-null  object
 71  SOPartFreq              10404 non-null  object
 72  SOJobs                  11546 non-null  object
 73  EntTeams                11547 non-null  object
 74  SOComm                  11552 non-null  object
 75  WelcomeChange           11463 non-null  object
 76  SONewContent            9557 non-null   object
 77  Age                     11255 non-null  float64
 78  Gender                  11477 non-null  object
 79  Trans                   11429 non-null  object
 80  Sexuality               11005 non-null  object
 81  Ethnicity               10869 non-null  object
 82  Dependents              11408 non-null  object
 83  SurveyLength            11533 non-null  object
 84  SurveyEase              11538 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 7.5+ MB

## Data Wrangling

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

#### Finding duplicates

In [7]:
df.duplicated().value_counts()

False    11398
True       154
dtype: int64

In [8]:
df['Respondent'].duplicated().value_counts()

False    11398
True       154
Name: Respondent, dtype: int64

#### Removing duplicates

In [9]:
df=df.drop_duplicates()
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

Verify if duplicates were actually dropped.

In [10]:
df.duplicated().value_counts()

False    11398
dtype: int64

In [11]:
df['Respondent'].duplicated().value_counts()

False    11398
Name: Respondent, dtype: int64

### Finding Missing values

In [12]:
df.isnull().sum()

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ...
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64

In [17]:
df_null=(100* df.isnull().sum()/len(df)).sort_values(ascending=False).to_frame()
df_null=df_null.rename(columns={0:'%missing_data'})
df_null=df_null[df_null['%missing_data']>0]
df_null

                    %missing_data
BlockchainIs            22.898754
CodeRevHrs              21.284436
BlockchainOrg           20.371995
MiscTechWorkedWith      19.143709
SONewContent            17.239867
...                           ...
JobFactors               0.026320
SOVisitTo                0.008773
SOAccount                0.008773
JobSat                   0.008773
CodeRev                  0.008773

[73 rows x 1 columns]

Find out how many rows are missing in the column 'WorkLoc', 'EdLevel', 'Country'

In [14]:
df['WorkLoc'].isnull().sum()

32

In [15]:
df['EdLevel'].isnull().sum()

112

In [16]:
df['Country'].isnull().sum()

0

#### Imputing missing values

I might do it step by step like this:

In [45]:
df['BlockchainIs'].value_counts()

Useful for immutable record keeping outside of currency                  5211
Useful across many domains and could change many aspects of our lives    2425
A passing fad                                                            1521
An irresponsible use of resources                                        1341
Useful for decentralized currency (i.e., Bitcoin)                         900
Name: BlockchainIs, dtype: int64

In [20]:
df['BlockchainIs'] = df['BlockchainIs'].fillna('Useful for immutable record keeping outside of currency')

In [21]:
df['CodeRevHrs'].value_counts()

2.00     1768
5.00     1657
4.00     1187
3.00     1117
1.00      989
10.00     660
8.00      522
6.00      379
15.00     152
7.00      107
20.00      83
12.00      72
0.50       46
0.00       38
1.50       24
25.00      20
2.50       19
16.00      19
9.00       16
30.00      13
14.00      12
40.00      11
50.00       6
0.10        6
0.25        5
7.50        5
18.00       4
17.00       3
35.00       3
0.01        3
13.00       3
99.00       2
0.20        2
0.05        2
21.00       2
60.00       1
28.00       1
54.00       1
90.00       1
11.00       1
6.50        1
45.00       1
0.40        1
24.00       1
0.30        1
36.00       1
22.00       1
7.19        1
48.00       1
52.00       1
Name: CodeRevHrs, dtype: int64

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [22]:
df['CodeRevHrs'] = df['CodeRevHrs'].fillna(df['CodeRevHrs'].mean())

A good idea is to check the percentage of missing values, and then decide what to do. I will do these check in order:
1. Too many: I will drop the column
2. A good percentage: I will fill the NaN with either the mean if the variable is numeric or the most recurring value if the variable is not numeric
3. Very few: I will drop all the NaN

In [37]:
df_null=(100* df.isnull().sum()/len(df)).sort_values(ascending=False).to_frame()
df_null=df_null.rename(columns={0:'%missing_data'})
df_null=df_null[df_null['%missing_data']>5]
df_null

                        %missing_data
BlockchainOrg               20.371995
MiscTechWorkedWith          19.143709
SONewContent                17.239867
SOHowMuchTime               16.818740
WebFrameDesireNextYear      14.186699
MiscTechDesireNextYear      12.765397
WebFrameWorkedWith          12.221442
SOPartFreq                   9.896473
DatabaseDesireNextYear       9.141955
ConvertedComp                7.159151
CompTotal                    7.097736
UndergradMajor               6.466047
Ethnicity                    5.922092

I do not have too many NaN so I will perform immediately the second task:

In [43]:
for i in df_null.index:
    print(i, ': ',df[i].dtypes)

BlockchainOrg :  object
MiscTechWorkedWith :  object
SONewContent :  object
SOHowMuchTime :  object
WebFrameDesireNextYear :  object
MiscTechDesireNextYear :  object
WebFrameWorkedWith :  object
SOPartFreq :  object
DatabaseDesireNextYear :  object
ConvertedComp :  float64
CompTotal :  float64
UndergradMajor :  object
Ethnicity :  object

Numeric variables:

In [46]:
list_of_numeric=[]
for i in df_null.index:
    if df[i].dtypes==int or df[i].dtypes==float:
        list_of_numeric.append(i)

list_of_numeric

['ConvertedComp', 'CompTotal']

In [50]:
for i in list_of_numeric:
    # filling with the mean of the class
    df[i] = df[i].fillna(df[i].mean())

Not numeric variables:

In [51]:
list_of_NOT_numeric=[]
for i in df_null.index:
    if df[i].dtypes==object:
        list_of_NOT_numeric.append(i)

list_of_NOT_numeric

['BlockchainOrg',
 'MiscTechWorkedWith',
 'SONewContent',
 'SOHowMuchTime',
 'WebFrameDesireNextYear',
 'MiscTechDesireNextYear',
 'WebFrameWorkedWith',
 'SOPartFreq',
 'DatabaseDesireNextYear',
 'UndergradMajor',
 'Ethnicity']

In [52]:
for i in list_of_NOT_numeric:
    # filling with the most recurrring of the class
    df[i] = df[i].fillna(df[i].value_counts().index[0])

In [54]:
df_null=(100* df.isnull().sum()/len(df)).sort_values(ascending=False).to_frame()
df_null=df_null.rename(columns={0:'%missing_data'})
df_null=df_null[df_null['%missing_data']>0]
df_null

                        %missing_data
PlatformDesireNextYear       4.772767
Sexuality                    4.755220
ScreenName                   4.448149
MgrMoney                     4.360414
MgrIdiot                     4.325320
MgrWant                      4.325320
DatabaseWorkedWith           3.974381
LastInt                      3.623443
PlatformWorkedWith           3.605896
SOVisit1st                   2.851377
SocialMedia                  2.570626
Age                          2.517986
CompFreq                     1.807335
PurchaseHow                  1.719600
EduOther                     1.438849
WorkChallenge                1.438849
Dependents                   1.228286
LanguageDesireNextYear       1.175645
Trans                        1.079137
WorkWeekHrs                  1.070363
WorkPlan                     1.061590
EdLevel                      0.982629
BetterLife                   0.859800
OrgSize                      0.842253
WelcomeChange                0.745745
Containers                   0.719424
OpenSource                   0.710651
Gender                       0.640463
DevType                      0.570275
Student                      0.447447
SOTimeSaved                  0.438673
ResumeUpdate                 0.342165
OffOn                        0.333392
PurchaseWhat                 0.333392
FizzBuzz                     0.324618
ITperson                     0.307071
OpSys                        0.298298
WorkLoc                      0.280751
DevEnviron                   0.254431
UnitTests                    0.254431
Extraversion                 0.175469
SurveyLength                 0.166696
YearsCodePro                 0.140376
SurveyEase                   0.122829
Age1stCode                   0.114055
LanguageWorkedWith           0.096508
YearsCode                    0.078961
WorkRemote                   0.070188
SOJobs                       0.052641
EntTeams                     0.043867
ImpSyn                       0.043867
SOVisitFreq                  0.043867
JobFactors                   0.026320
SOFindAnswer                 0.026320
SOAccount                    0.008773
SOVisitTo                    0.008773
JobSat                       0.008773
CodeRev                      0.008773

I will drop the NaN for the variables with very few NaN: (I can do like that because I do not have other great missing values):

In [55]:
df.dropna(inplace=True)

Now I shoud have 0 missing values:

In [56]:
df_null=(100* df.isnull().sum()/len(df)).sort_values(ascending=False).to_frame()
df_null=df_null.rename(columns={0:'%missing_data'})
df_null=df_null[df_null['%missing_data']>0]
df_null

Empty DataFrame
Columns: [%missing_data]
Index: []

### Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

I will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq', this will make comparison of salaries easy.

In [57]:
df[['CompFreq','CompTotal']].head()

  CompFreq  CompTotal
1   Yearly   138000.0
5  Monthly     9500.0
6  Monthly     3000.0
7   Yearly   103000.0
8   Yearly    69000.0

In [58]:
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly'], dtype=object)

In [59]:
df['CompFreq'].value_counts()

Yearly     3493
Monthly    2654
Weekly      186
Name: CompFreq, dtype: int64

I will find the multiplier to get the Annual compensation:

In [61]:
def change(frequence):
    if frequence =='Yearly':
        n=1
    if frequence =='Monthly':
        n=12
    if frequence =='Weekly':
        n=52
        
    return n

In [62]:
df['multiplier']=df['CompFreq'].apply(change)

In [63]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase,multiplier
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,1
5,19,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Brazil,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,Yes,Too long,Easy,12
6,20,"I am not primarily a developer, but I write co...",No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Lithuania,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",...,Tech articles written by other developers,38.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,12
7,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,1
8,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,Tech articles written by other developers;Tech...,22.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy,1

In [66]:
df['NormalizedAnnualCompensation']=df['CompTotal']*df['multiplier']
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase,multiplier,NormalizedAnnualCompensation
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,1,138000.0
5,19,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Brazil,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,31.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,Yes,Too long,Easy,12,114000.0
6,20,"I am not primarily a developer, but I write co...",No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Lithuania,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",...,38.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,12,36000.0
7,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,1,103000.0
8,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,22.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy,1,69000.0

In [67]:
df.to_csv('tech.csv')